STCC_NEW_MASTER_RPL_CONFIG = {
    "FILE_NAME": "STCC_NEW_MASTER_RPL",
    "TXT_EXT": ".txt",
    "ZIP_EXT": ".zip",
    "ARCHIVE_PATH": "archive",
    "WORK_PATH": "work",
    "length_of_row": {
        "a": 2,
        "b": 5,
        "c": 10
    },
    "columns": [
        "STCC_ID",
        "STCC_CODE",
        "SIC_CODE",
        "ISIC_CODE",
        "SCTG_CODE",
        "STCC50_CODE",
        "TRANS_DATE",
        "TRANS_TIME",
        "TRANSACTION_CODE",
        "HARMONY_CODE",
        "CS54_GROUP_CODE",
        "CS54_GROUP_NAME",
        "DEREGULATION_CODE",
        "DEREG_DATE",
        "MINIMUM_CAR_GRADE",
        "EFF_DATE",
        "PRODUCT_DESC",
        "PRODUCT_SHORT_DESC",
        "ALTERNATE_NBR",
        "NEW_STCC_CODE",
        "EXP_DATE",
        "DELETE_DATE"
    ],
    "result_column": [
        ["STCC_CODE", 7, "R", " "],
        ["STCC50_CODE", 7, "R", " "],
        ["TRANS_DATE", 8, "L", "0"],
        ["TRANS_HOUR", 2, "L", "0"],
        ["TRANS_MINUTE", 2, "L", "0"],
        ["TRANS_SECOND", 2, "L", "0"],
        ["TRANSACTION_CODE", 1, "R", " "],
        ["HARMONY_CODE1", 12, "R", " "],
        ["HARMONY_CODE2", 12, "R", " "],
        ["HARMONY_CODE3", 12, "R", " "],
        ["HARMONY_CODE4", 12, "R", " "],
        ["HARMONY_CODE5", 12, "R", " "],
        ["HARMONY_CODE6", 12, "R", " "],
        ["HARMONY_CODE7", 12, "R", " "],
        ["HARMONY_CODE8", 12, "R", " "],
        ["HARMONY_CODE9", 12, "R", " "],
        ["HARMONY_CODE10", 12, "R", " "],
        ["SIC_CODE1", 4, "R", " "],
        ["SIC_CODE2", 4, "R", " "],
        ["SIC_CODE3", 4, "R", " "],
        ["SIC_CODE4", 4, "R", " "],
        ["SIC_CODE5", 4, "R", " "],
        ["SIC_CODE6", 4, "R", " "],
        ["SIC_CODE7", 4, "R", " "],
        ["SIC_CODE8", 4, "R", " "],
        ["ISIC_CODE1", 4, "R", " "],
        ["ISIC_CODE2", 4, "R", " "],
        ["ISIC_CODE3", 4, "R", " "],
        ["ISIC_CODE4", 4, "R", " "],
        ["ISIC_CODE5", 4, "R", " "],
        ["ISIC_CODE6", 4, "R", " "],
        ["ISIC_CODE7", 4, "R", " "],
        ["ISIC_CODE8", 4, "R", " "],
        ["SCTG_CODE", 5, "R", " "],
        ["CS54_GROUP_CODE", 2, "R", " "],
        ["CS54_GROUP_NAME", 30, "R", " "],
        ["DEREGULATION_CODE", 1, "R", " "],
        ["DEREG_DATE", 8, "R", " "],
        ["MINIMUM_CAR_GRADE", 1, "R", " "],
        ["EFF_DATE", 8, "R", " "],
        ["STCC_CODE2", 2, "R", " "],
        ["STCC_CODE3", 3, "R", " "],
        ["STCC_CODE4", 4, "R", " "],
        ["STCC_CODE5", 5, "R", " "],
        ["PRODUCT_DESC", 2500, "R", " "],
        ["PRODUCT_SHORT_DESC", 15, "R", " "],
        ["ALTERNATE_NBR", 2, "L", "0"],
        ["NEW_STCC_CODE", 7, "R", " "],
        ["EXP_DATE", 8, "R", " "],
        ["DELETE_DATE", 8, "R", " "],
        ["SPACE", 3, "R", " "],
    ],
    "duplicate_key": {
        "STCC_STD_INDSTR_CLASSIFICATION": 8,
        "STCC_SCTG": 10
    }
}
IRFHMDB1_CONFIG = {
    "FILE_NAME": "IRFHMDB1",
    "TXT_EXT": ".txt",
    "ZIP_EXT": ".zip",
    "ARCHIVE_PATH": "archive",
    "IRFHMDB1_CONFIG": "ADD ID=AAR2 RECEIVER=BNSF BATCHID='IRFHMDB1' PASSWORD=PASSWORD",
    "columns": [
        "HAZMAT_CODE",
        "STCC_CODE",
        "TRANS_DATE",
        "TRANS_TIME",
        "TRANS_CODE",
        "EFF_DATE",
        "HEADER1",
        "HEADER2",
        "HEADER3",
        "HEADER4",
        "PROD_DESC_15CHAR",
        "ALTERNATIVE_NUMBER",
        "EXP_DATE",
        "PROP_SHIP_ALPHA",
        "IMO_CLASS",
        "INOS_IND",
        "ITECHNAME",
        "IUN_NA_NUM",
        "IPACKING_GROUP",
        "IPOISON_MAT_IND",
        "IPROPNAME",
        "IPRI_PLACARD_NOT",
        "CPRI_CL",
        "CSEC_CL1",
        "CSEC_CL2",
        "CSEC_CL3",
        "CCANO_USDEST",
        "CERP_IND",
        "CPRI_PLACARD_NOT",
        "CSPEC_COMM_IND",
        "CSUB_RISK_IND",
        "CNOS_IND",
        "CSEC_PLACARD_NOT",
        "CTECHNAME",
        "CUN_NA_NUM",
        "CPACKING_GRP",
        "CPOISON_MAT_IND",
        "CPRI_PSN",
        "NEPA_WASTCHAR1",
        "NEPA_WASTCHAR2",
        "NEPA_WASTCHAR3",
        "NEPA_WASTSTRM1",
        "NEPA_WASTSTRM2",
        "NEPA_WASTSTRM3",
        "NHAZ_PLA_ENDOR",
        "NPRI_CL",
        "NSEC_CL1",
        "NSEC_CL2",
        "HAZ_ZONE",
        "NNOS_IND",
        "NSEC_PLACARD_NOT",
        "NTECHNAME",
        "NUN_NA_NUM",
        "NUSO_CAND_FLAG",
        "NPACKING_GRP",
        "NPOISON_MAT_IND",
        "NPRI_PLACARD_NOT",
        "NPRI_PSN",
        "OT55_FLAG",
        "DANGER_WHEN_WET",
        "REPORTABLE_QTY",
        "MAR_POLL_FLAG",
        "HAZ_SUB_NAME",
        "MAR_POLL_NAME",
        "CPRI_CL2",
        "CSPECIAL_PSN_FLAG",
        "ISPECIAL_PSN_FLAG",
        "NSPECIAL_PSN_FLAG",
        "CINTL_IND",
        "IINTL_IND",
        "NINTL_IND",
        "CAPPROVED_TANKCAR",
        "NAPPROVED_TANKCAR",
        "ALPHA_DESC",
        "PCSTCC_DESC",
        "ISEC_PLACARD_NOT",
        "ISEC_CL1",
        "ISEC_CL2",
        "ISEC_CL3",
        "DELETE_DATE",
        "CPSN", "IPSN",
        "NPSN",
        "CPSN_SEQ",
        "IPSN_SEQ",
        "NPSN_SEQ",
        "ADD_DATE",
        "LAST_UPD_DATE"],

    "result_column": [
        ["HAZMAT_CODE", 7, "R", " "],
        ["STCC_CODE", 7, "R", " "],
        ["TRANS_DATE", 8, "R", " "],
        ["TRANS_TIME", 6, "R", " "],
        ["TRANS_CODE", 1, "R", " "],
        ["EFF_DATE", 8, "R", " "],
        ["HEADER1", 2, "R", " "],
        ["HEADER2", 3, "R", " "],
        ["HEADER3", 4, "R", " "],
        ["HEADER4", 5, "R", " "],
        ["PROD_DESC_15CHAR", 15, "R", " "],
        ["ALTERNATIVE_NUMBER", 2, "R", " "],
        ["EXP_DATE", 8, "R", " "],
        ["PROP_SHIP_ALPHA", 250, "R", " "],
        ["IMO_CLASS", 4, "R", " "],
        ["INOS_IND", 1, "R", " "],
        ["ITECHNAME", 125, "R", " "],
        ["IUN_NA_NUM", 6, "R", " "],
        ["IPACKING_GROUP", 1, "R", " "],
        ["IPOISON_MAT_IND", 1, "R", " "],
        ["IPRI_PLACARD_NOT", 2, "R", " "],
        ["IPROPNAME", 125, "R", " "],
        ["CPRI_CL", 4, "R", " "],
        ["CSEC_CL1", 3, "R", " "],
        ["CSEC_CL2", 3, "R", " "],
        ["CSEC_CL3", 3, "R", " "],
        ["CCANO_USDEST", 1, "R", " "],
        ["CERP_IND", 4, "R", " "],
        ["CPRI_PLACARD_NOT", 2, "R", " "],
        ["CSPEC_COMM_IND", 1, "R", " "],
        ["CSUB_RISK_IND", 1, "R", " "],
        ["CNOS_IND", 1, "R", " "],
        ["CSEC_PLACARD_NOT", 2, "R", " "],
        ["CTECHNAME", 125, "R", " "],
        ["CUN_NA_NUM", 6, "R", " "],
        ["CPACKING_GRP", 1, "R", " "],
        ["CPOISON_MAT_IND", 1, "R", " "],
        ["CPRI_PSN", 125, "R", " "],
        ["NEPA_WASTCHAR1", 1, "R", " "],
        ["NEPA_WASTCHAR2", 1, "R", " "],
        ["NEPA_WASTCHAR3", 1, "R", " "],
        ["NEPA_WASTSTRM1", 6, "R", " "],
        ["NEPA_WASTSTRM2", 6, "R", " "],
        ["NEPA_WASTSTRM3", 6, "R", " "],
        ["NHAZ_PLA_ENDOR", 2, "R", " "],
        ["NPRI_CL", 4, "R", " "],
        ["NSEC_CL1", 3, "R", " "],
        ["NSEC_CL2", 3, "R", " "],
        ["HAZ_ZONE", 1, "R", " "],
        ["NNOS_IND", 1, "R", " "],
        ["NSEC_PLACARD_NOT", 2, "R", " "],
        ["NTECHNAME", 125, "R", " "],
        ["NUN_NA_NUM", 6, "R", " "],
        ["NUSO_CAND_FLAG", 1, "R", " "],
        ["NPACKING_GRP", 1, "R", " "],
        ["NPOISON_MAT_IND", 1, "R", " "],
        ["NPRI_PLACARD_NOT", 2, "R", " "],
        ["NPRI_PSN", 125, "R", " "],
        ["OT55_FLAG", 1, "R", " "],
        ["DANGER_WHEN_WET", 1, "R", " "],
        ["REPORTABLE_QTY", 1, "R", " "],
        ["MAR_POLL_FLAG", 1, "R", " "],
        ["HAZ_SUB_NAME", 125, "R", " "],
        ["MAR_POLL_NAME", 125, "R", " "],
        ["CPRI_CL2", 4, "R", " "],
        ["CSPECIAL_PSN_FLAG", 1, "R", " "],
        ["ISPECIAL_PSN_FLAG", 1, "R", " "],
        ["NSPECIAL_PSN_FLAG", 1, "R", " "],
        ["CINTL_IND", 1, "R", " "],
        ["IINTL_IND", 1, "R", " "],
        ["NINTL_IND", 1, "R", " "],
        ["CAPPROVED_TANKCAR", 2, "R", " "],
        ["NAPPROVED_TANKCAR", 2, "R", " "],
        ["ALPHA_DESC", 250, "R", " "],
        ["PCSTCC_DESC", 250, "R", " "],
        ["ISEC_PLACARD_NOT", 2, "R", " "],
        ["ISEC_CL1", 3, "R", " "],
        ["ISEC_CL2", 3, "R", " "],
        ["ISEC_CL3", 3, "R", " "],
        ["DELETE_DATE", 8, "R", " "],
        ["CPSN1", 125, "R", " "],
        ["CPSN2", 125, "R", " "],
        ["CPSN3", 125, "R", " "],
        ["CPSN4", 125, "R", " "],
        ["CPSN5", 125, "R", " "],
        ["IPSN1", 125, "R", " "],
        ["IPSN2", 125, "R", " "],
        ["IPSN3", 125, "R", " "],
        ["IPSN4", 125, "R", " "],
        ["IPSN5", 125, "R", " "],
        ["NPSN1", 125, "R", " "],
        ["NPSN2", 125, "R", " "],
        ["NPSN3", 125, "R", " "],
        ["NPSN4", 125, "R", " "],
        ["NPSN5", 125, "R", " "],
        ["SPACE", 113, "R", " "],
    ]
}
